# Generated by Django 2.1.7 on 2019-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('red', 'High'), ('orange', 'Mid'), ('white', 'Low')], max_length=6),
        ),
    ]
