# Generated by Django 2.1.7 on 2019-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20190402_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colour',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
