# Generated by Django 2.1.7 on 2019-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_auto_20190403_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colour',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('white', 'Low'), ('orange', 'Mid'), ('red', 'High')], default='white', max_length=6),
        ),
    ]
